DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
	userid INTEGER PRIMARY KEY AUTOINCREMENT,
	firstname VARCHAR(20),
	lastname VARCHAR(20),
	email VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL
);